# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: ebfe2145020743da74bc03c2995e5e32a44731c75427ed1f60922a28a5f590ac4322f2599d7d9c2dfd9c18a9b50b37135b7c58a5d3769b2662fec057b0c479c2

test:
  secret_key_base: 016d173195816926d85e58de25d7ec813497ba7af5bdbec3920a462502389d4aaad8f7635929c224906245303f290021a51e70f18ef40108601b10850980c7a5

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
