# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: d8315b115251891c509f704cdafe98e18497cde2ba95cec93e1c5ab8688ae47adb0d89757df89de99c36b617e987e1363ab27f16aac1e5e159f52d70866d6022

test:
  secret_key_base: 3406b448dd8ad0b2a40ab9b48f73156728c4d60198ba3c90157aae5b5e7c09a3b711f370a76f0dd5ce181a1d3209b6172390cdfe0857600303e8434b5e76ef8b

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
